
import "./globals.css";
import Navbar from "../components/Navbar";
import Footer from "../components/Footer";
import  { ProductsProvider } from "@/context/ProductsContext";




export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children}) {
  return (
    <html lang="en">
      <body
        className="bg-[#9CAA96] scrollbar-hide"
      >
        <ProductsProvider>
          <Navbar/>
          {children}
          <Footer/>
        </ProductsProvider>
      </body>
    </html>
  );
}



